{"task_id": 370, "prediction_id": 0, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        os.environ.get(ENV_XDG_CONFIG_HOME, None),\n        os.environ.get(ENV_HTTPIE_CONFIG_DIR, None),\n        DEFAULT_CONFIG_DIRNAME,\n        DEFAULT_RELATIVE_XDG_CONFIG_HOME,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 66, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 1, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return DEFAULT_WINDOWS_CONFIG_DIR if is_windows else DEFAULT_CONFIG_DIRNAME\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 153, in <module>\n  File \"<string>\", line 152, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 2, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    if ENV_XDG_CONFIG_HOME:\n        return Path(os.environ[ENV_XDG_CONFIG_HOME])\n    else:\n        return DEFAULT_CONFIG_DIR\n\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 65, in <module>\n  File \"<string>\", line 58, in get_default_config_dir\n  File \"/usr/local/lib/python3.10/os.py\", line 679, in __getitem__\n    raise KeyError(key) from None\nKeyError: 'XDG_CONFIG_HOME'\n", "passed": false}
{"task_id": 370, "prediction_id": 3, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        os.environ.get(ENV_XDG_CONFIG_HOME, None),\n        os.environ.get(ENV_HTTPIE_CONFIG_DIR, None),\n        DEFAULT_CONFIG_DIRNAME,\n        DEFAULT_RELATIVE_XDG_CONFIG_HOME,\n        DEFAULT_RELATIVE_LEGACY_CONFIG_DIR,\n        DEFAULT_WINDOWS_CONFIG_DIR,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 68, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 4, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    if ENV_XDG_CONFIG_HOME:\n        return Path(os.environ[ENV_XDG_CONFIG_HOME])\n    else:\n        return Path(DEFAULT_CONFIG_DIRNAME)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 64, in <module>\n  File \"<string>\", line 58, in get_default_config_dir\n  File \"/usr/local/lib/python3.10/os.py\", line 679, in __getitem__\n    raise KeyError(key) from None\nKeyError: 'XDG_CONFIG_HOME'\n", "passed": false}
{"task_id": 370, "prediction_id": 5, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return DEFAULT_WINDOWS_CONFIG_DIR if is_windows else Path(\n        os.environ.get(ENV_XDG_CONFIG_HOME,\n                       os.path.expanduser(DEFAULT_CONFIG_DIRNAME)))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 155, in <module>\n  File \"<string>\", line 154, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 6, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        env_var=ENV_XDG_CONFIG_HOME,\n        default=DEFAULT_CONFIG_DIRNAME,\n        relative_to=DEFAULT_RELATIVE_XDG_CONFIG_HOME,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 65, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 7, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_RELATIVE_XDG_CONFIG_HOME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 8, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    if ENV_XDG_CONFIG_HOME:\n        return Path(os.environ[ENV_XDG_CONFIG_HOME])\n    else:\n        return Path(DEFAULT_CONFIG_DIRNAME)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 64, in <module>\n  File \"<string>\", line 58, in get_default_config_dir\n  File \"/usr/local/lib/python3.10/os.py\", line 679, in __getitem__\n    raise KeyError(key) from None\nKeyError: 'XDG_CONFIG_HOME'\n", "passed": false}
{"task_id": 370, "prediction_id": 9, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_RELATIVE_XDG_CONFIG_HOME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 10, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return DEFAULT_WINDOWS_CONFIG_DIR if is_windows else DEFAULT_CONFIG_DIRNAME\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 153, in <module>\n  File \"<string>\", line 152, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 11, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        env_var=ENV_XDG_CONFIG_HOME,\n        default=DEFAULT_CONFIG_DIRNAME,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 64, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 12, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path.home() / '.config' / DEFAULT_CONFIG_DIRNAME\n", "message": "passed", "passed": true}
{"task_id": 370, "prediction_id": 13, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_RELATIVE_XDG_CONFIG_HOME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 14, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        env_var=ENV_XDG_CONFIG_HOME,\n        default=DEFAULT_CONFIG_DIRNAME,\n        relative_to=DEFAULT_RELATIVE_XDG_CONFIG_HOME,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 65, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 15, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_RELATIVE_XDG_CONFIG_HOME))\n\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 155, in <module>\n  File \"<string>\", line 154, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 16, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        config_dir=DEFAULT_CONFIG_DIRNAME,\n        config_dir_name=DEFAULT_CONFIG_DIRNAME,\n        config_dir_path=DEFAULT_WINDOWS_CONFIG_DIR,\n        config_dir_path_is_windows=True,\n        config_dir_path_is_legacy=False,\n        config_dir_path_is_relative=False,\n        config_dir_path_is_absolute=False,\n        config_dir_path_is_envvar=False,\n        config_dir_path_is_envvar_env=False,\n        config_dir_path_is_envvar_env_is_windows=False,\n        config_dir_path_is_envvar_env_is_windows_is_legacy=False,\n        config_dir_path_is_envvar_env_is_windows_is_legacy_is_relative=False,\n        config_dir_path_is_envvar_env_is_windows_is_legacy_is_relative_is_absolute=False,\n        config_dir_path_is_envvar_env_is_windows_is_legacy_is_relative_is_absolute_is_envvar=False,\n        config_dir_path_is_envvar_env_is_windows_is_legacy_is_relative_is_absolute_is_envvar_env=False,\n        config_dir_path_is_envvar_env_is_windows_is_legacy_is_relative_is_absolute_is_envvar_env_is_windows=False,\n        config_dir_path_is_envvar_env_is_windows_is_legacy_is_relative_is_absolute_is_envvar_env_is_windows_is_relative=False,\n        config_dir_path_is_envvar_env_is_windows_is_legacy_is_relative_is_absolute_is_envvar_env_is_windows_is_legacy_is_relative_is_absolute_is_envvar=False,\n        config_dir_path_is_envvar_env_is", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 76\n    config_dir_path_is_envvar_env_is\n    ^^^^^^^^^^\nSyntaxError: invalid syntax. Perhaps you forgot a comma?\n", "passed": false}
{"task_id": 370, "prediction_id": 17, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        default_dirname=DEFAULT_CONFIG_DIRNAME,\n        default_relative_dir=DEFAULT_RELATIVE_XDG_CONFIG_HOME,\n        default_windows_dir=DEFAULT_WINDOWS_CONFIG_DIR,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 65, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 18, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        os.environ.get(ENV_XDG_CONFIG_HOME, None),\n        os.environ.get(ENV_HTTPIE_CONFIG_DIR, None),\n        DEFAULT_CONFIG_DIRNAME,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 65, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 19, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(DEFAULT_CONFIG_DIRNAME)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 61, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 20, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_RELATIVE_XDG_CONFIG_HOME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 21, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_RELATIVE_XDG_CONFIG_HOME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 22, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_CONFIG_DIRNAME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 23, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               Path.home() / '.config'))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 24, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        env_var=ENV_XDG_CONFIG_HOME,\n        default_dir=DEFAULT_CONFIG_DIRNAME,\n        relative_to=DEFAULT_RELATIVE_XDG_CONFIG_HOME,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 65, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 25, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_RELATIVE_XDG_CONFIG_HOME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 26, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return DEFAULT_WINDOWS_CONFIG_DIR if is_windows else DEFAULT_CONFIG_DIRNAME\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 153, in <module>\n  File \"<string>\", line 152, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 27, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_RELATIVE_XDG_CONFIG_HOME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 28, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    if ENV_XDG_CONFIG_HOME:\n        return Path(os.environ[ENV_XDG_CONFIG_HOME])\n    else:\n        return Path.home() / '.config'\n\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 65, in <module>\n  File \"<string>\", line 58, in get_default_config_dir\n  File \"/usr/local/lib/python3.10/os.py\", line 679, in __getitem__\n    raise KeyError(key) from None\nKeyError: 'XDG_CONFIG_HOME'\n", "passed": false}
{"task_id": 370, "prediction_id": 29, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return DEFAULT_WINDOWS_CONFIG_DIR if is_windows else DEFAULT_CONFIG_DIRNAME\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 153, in <module>\n  File \"<string>\", line 152, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 30, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_CONFIG_DIRNAME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 31, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        os.environ.get(ENV_XDG_CONFIG_HOME, None),\n        os.environ.get(ENV_HTTPIE_CONFIG_DIR, None),\n        DEFAULT_CONFIG_DIRNAME,\n        DEFAULT_RELATIVE_XDG_CONFIG_HOME,\n        DEFAULT_RELATIVE_LEGACY_CONFIG_DIR,\n        DEFAULT_WINDOWS_CONFIG_DIR,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 68, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 32, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        os.environ.get(ENV_XDG_CONFIG_HOME, None),\n        os.environ.get(ENV_HTTPIE_CONFIG_DIR, None),\n        DEFAULT_CONFIG_DIRNAME,\n        DEFAULT_RELATIVE_XDG_CONFIG_HOME,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 66, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 33, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(DEFAULT_CONFIG_DIRNAME)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 61, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 34, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    if os.name == 'nt':\n        return DEFAULT_WINDOWS_CONFIG_DIR\n    elif is_windows:\n        return DEFAULT_WINDOWS_CONFIG_DIR\n    else:\n        return Path.home() / ENV_XDG_CONFIG_HOME\n\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 159, in <module>\n  File \"<string>\", line 158, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 35, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return DEFAULT_WINDOWS_CONFIG_DIR if is_windows else DEFAULT_CONFIG_DIRNAME\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 153, in <module>\n  File \"<string>\", line 152, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 36, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path.home() / '.config' / DEFAULT_CONFIG_DIRNAME\n", "message": "passed", "passed": true}
{"task_id": 370, "prediction_id": 37, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        os.environ.get(ENV_XDG_CONFIG_HOME, None),\n        os.environ.get(ENV_HTTPIE_CONFIG_DIR, None),\n        DEFAULT_CONFIG_DIRNAME,\n        DEFAULT_RELATIVE_XDG_CONFIG_HOME,\n        DEFAULT_RELATIVE_LEGACY_CONFIG_DIR,\n        DEFAULT_WINDOWS_CONFIG_DIR,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 68, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 38, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_RELATIVE_XDG_CONFIG_HOME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 39, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_RELATIVE_XDG_CONFIG_HOME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 40, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_CONFIG_DIRNAME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 41, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME, DEFAULT_CONFIG_DIRNAME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 153, in <module>\n  File \"<string>\", line 152, in test_2\nAssertionError\n", "passed": false}
{"task_id": 370, "prediction_id": 42, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path.home() / '.config' / DEFAULT_CONFIG_DIRNAME\n", "message": "passed", "passed": true}
{"task_id": 370, "prediction_id": 43, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        os.environ.get(ENV_XDG_CONFIG_HOME, None),\n        os.environ.get(ENV_HTTPIE_CONFIG_DIR, None),\n        DEFAULT_CONFIG_DIRNAME,\n        DEFAULT_RELATIVE_XDG_CONFIG_HOME,\n        DEFAULT_RELATIVE_LEGACY_CONFIG_DIR,\n        DEFAULT_WINDOWS_CONFIG_DIR,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 68, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 44, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        os.environ.get(ENV_XDG_CONFIG_HOME, None),\n        os.environ.get(ENV_HTTPIE_CONFIG_DIR, None),\n        DEFAULT_CONFIG_DIRNAME,\n        DEFAULT_RELATIVE_XDG_CONFIG_HOME,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 66, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 45, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    if ENV_XDG_CONFIG_HOME:\n        return Path(os.environ[ENV_XDG_CONFIG_HOME])\n    else:\n        return Path.home() / '.config'\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 64, in <module>\n  File \"<string>\", line 58, in get_default_config_dir\n  File \"/usr/local/lib/python3.10/os.py\", line 679, in __getitem__\n    raise KeyError(key) from None\nKeyError: 'XDG_CONFIG_HOME'\n", "passed": false}
{"task_id": 370, "prediction_id": 46, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        os.environ.get(ENV_XDG_CONFIG_HOME, None),\n        os.environ.get(ENV_HTTPIE_CONFIG_DIR, None),\n        DEFAULT_CONFIG_DIRNAME,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 65, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 47, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(DEFAULT_CONFIG_DIRNAME)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 61, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 48, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return get_config_dir(\n        os.environ.get(ENV_XDG_CONFIG_HOME, None),\n        os.environ.get(ENV_HTTPIE_CONFIG_DIR, None),\n        DEFAULT_CONFIG_DIRNAME,\n    )\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 65, in <module>\n  File \"<string>\", line 57, in get_default_config_dir\nNameError: name 'get_config_dir' is not defined\n", "passed": false}
{"task_id": 370, "prediction_id": 49, "generation": "def get_default_config_dir() -> Path:\n    \"\"\"\n    Return the path to the httpie configuration directory.\n\n    This directory isn't guaranteed to exist, and nor are any of its\n    ancestors (only the legacy ~/.httpie, if returned, is guaranteed to exist).\n\n    XDG Base Directory Specification support:\n\n    <https://wiki.archlinux.org/index.php/XDG_Base_Directory>\n\n    $XDG_CONFIG_HOME is supported; $XDG_CONFIG_DIRS is not\n\n    \"\"\"\n    return Path(os.environ.get(ENV_XDG_CONFIG_HOME,\n                               DEFAULT_RELATIVE_XDG_CONFIG_HOME))\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 154, in <module>\n  File \"<string>\", line 153, in test_2\nAssertionError\n", "passed": false}
